# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: python

cache: pip

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: 
    - pip install --upgrade setuptools pip
    - pip install --upgrade -r requirements/test.txt
    - pip install --upgrade .
before_script:
    - pytest --version
# command to run tests, e.g. python setup.py test
script:
    - pytest -vv --cov
after_success:
    - if [[ ${COVERALLS} == true ]]; then coveralls; fi

branches:
  only:
  - master
  - /^v(?<major>0|[1-9]\d*)\.(?<minor>0|[1-9]\d*)\.(?<patch>0|[1-9]\d*)(?:-(?<prerelease>(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+(?<buildmetadata>[0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/ # SemVer tags (https://github.com/semver/semver/issues/232#issuecomment-405596809)

jobs:
    fast_finish: true
    allow_failures:
        - python: "3.6-dev"
        - python: "3.7-dev"
        - python: "3.8-dev"
    include:
        - python: "3.6"
        - python: "3.6-dev"
        - python: "3.7"
        - python: "3.7-dev"
        - python: "3.8"
        - python: "3.8-dev"
        - python: "3.9-dev"

        - stage: pylint
          python: "3.8"
          script:
            - pylint --disable=fixme --fail-under=9.5 pycgbuilder
          after_success: skip

        - stage: deploy
          python: "3.8"
          before_script: skip
          script: skip
          deploy:
            provider: pypi
            user: pckroon
            password:
              secure: "BX61qcAQeYfMAELVrLB5SEq2JMXBSU+XTrK7ZjqQodtSnVOlnH6yUAZCWuXCni7XvQ30efO2toD9HCOpzfM19Dbe/64+2pwpZTxeHqSLPRmGGkfy18N5TXQcLNZfiEO/XdYTr2S9E3d5CXniKZ8PP6ivN9JTek0Mv4PS4yFes+ILRgBdCNVdS2GQI/2hXwzLgBzXwMqG6j2SIUk8aR4rBjnSXZ4xiJAFlVGL2ert7pWEat/mVGsMNUc7HyDUrpb27KCP3v5innulXY/gE0D2LvEUPHkuNqkZ8d9PxBsh39QMiulaJTR5CtB/Q1e/C/BZi9YuXLc2/bIFo0x5uLu053okTJMOFKP4+XJ2dIsvQovPslbPyS9ZuBIJjGfvpO6LKCQTkmDni00O/V+0af8i3Tt3n/gAvPm1Ozpz8gyJbelweJc1Ip0xDpgw9d/NpsPnIKzuT4Ktt9x6CzBt+6/OAehRtCcii7cF3pnA5s9ilqaNTkLjqdVQUQ1Hf4CErtcVhROluMYaFKtZ3ONl+40zNGyWAPnvfZsQVYCUsqn5DymB50J9wpTAn1nxl03AdK4pbxDRTVTc0/5zlLrkB8BpSW1F1wLtynaclcqJUGJSf8jiROtBFJb2eBgldchryWWwOrUTWXO+6etee3F3+qRuEg3baw9ZG4zPMp9Nvp8iA5g=" 
            on:
              tags: true





